### ISSUE TITLE
[Errno 36] File name too long

### ISSUE THREAD

**Issue by whliu90** [polixir/RLAssistant#15]
when run the code 
`exp_manager.log_files_gen()`
, I got this error:

`[Errno 36] File name too long: './code/test_task/2022/11/10/08-47-50-601532_172.17.0.8_&data_type=S_Mon_S_Period&seed=0/code/ccdc_cql_transformer_hc/2022/11/10/08-42-17-143559_172.17.0.8_&data_type=S_Mon_S_Period&seed=0/code/ccdc_cql_transformer_hc/2022/11/10/08-42-17-143559_172.17.0.8_&data_type=S_Mon_S_Period&seed=0/code/ccdc_cql_transformer_hc/2022/11/10/08-42-17-143559_172.17.0.8_&data_type=S_Mon_S_Period&seed=0/code/ccdc_cql_transformer_hc/2022/11/10/08-42-17-143559_172.17.0.8_&data_type=S_Mon_S_Period&seed=0/code/ccdc_cql_transformer_hc/2022/11/10/08-42-17-143559_172.17.0.8_&data_type=S_Mon_S_Period&seed=0/code/ccdc_cql_transformer_hc/2022/11/10/08-42-17-...'`

could you help me to fix this question?

**Comment by xionghuichen** [comment]
It is because the ``code``  folder is recursively copied. 

RLA will back up your projects (defined by BACKUP_CONFIG.backup_code_dir in rla_config.yaml) into the ``{data_root}/{task_table_name}/code`` folder when starting your main script.  However, currently, the ``code`` folder is also under ``BACKUP_CONFIG.backup_code_dir``, so the ``code`` folder is recursively copied. 

There are several solutions. I think the simplest way is using the ``ignore_file_path'' parameter. For example, you can config the exp_manager like this:
```python
def get_package_path():
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

exp_manager.configure(task_table_name='test_task',
                      rla_config=os.path.join(get_package_path(), 'rla_config.yaml'),
                      ignore_file_path=os.path.join(get_package_path(), '.gitignore'),
                      data_root=get_package_path())
```
where `os.path.join(get_package_path(), '.gitignore')` should at least include the following contents:
```
**/archive_tester/**
**/checkpoint/**
**/code/**
**/results/**
**/log/**
**/arc/**
```
Then the related contents will be ignored when backing up your project.

Please tell me if the solution cannot handle your problem. :)

**Comment by whliu90** [comment]
Thanks so much. It seems that there is a folder named `code`, which is my 'BACKUP_CONFIG.backup_code_dir', under the `data_root`. Thus, the `code` folder is recursively copied. I fixed it by configuring the `data_root` with an empty directory.

One more thing, when I use the RLA, I am confused by which package I should import. For exmple:
`from RLA.easy_log.tester import exp_manager`  # in examples
or
`from RLA import exp_manager` # in README.md

Thanks again.

**Comment by xionghuichen** [comment]
Cool! Both are ok. `RLA.exp_manager` is a reference to the exp_manager in `RLA.easy_log.tester.exp_manager`.  refer to https://github.com/polixir/RLAssistant/blob/f8f34e76a810916858815d8eef09fc237b368999/RLA/__init__.py#L1

**Comment by whliu90** [comment]
O! I got it. Haha, thank you very much!
